version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.10.0-stretch-browsers
    steps:
      - checkout
      - run: npm install
      - run: snyk test
  test:
    docker:
      - image: circleci/node:8.10.0-stretch-browsers
    steps:
      - checkout
      - run: npm run test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test